services:
  db_students:
    image: postgres
    container_name: db_students
    restart: always
    ports:
      - 2300:5432
    env_file:
      - .env
    volumes:
      - students:/var/lib/postgresql/data

  node_app_students:
    container_name: students_node
    build: .
    ports:
      - 5009:5000
    depends_on:
      - db_students
    env_file:
      - .env

volumes:
  students: